//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.SnippetDesigner {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.SnippetDesigner.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not complete the save operation..
        /// </summary>
        internal static string BadSaveFlags {
            get {
                return ResourceManager.GetString("BadSaveFlags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not create tool window..
        /// </summary>
        internal static string CanNotCreateWindow {
            get {
                return ResourceManager.GetString("CanNotCreateWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code Snippet.
        /// </summary>
        internal static string CodeSnippet {
            get {
                return ResourceManager.GetString("CodeSnippet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C++.
        /// </summary>
        internal static string DisplayNameCPP {
            get {
                return ResourceManager.GetString("DisplayNameCPP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C#.
        /// </summary>
        internal static string DisplayNameCSharp {
            get {
                return ResourceManager.GetString("DisplayNameCSharp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTML.
        /// </summary>
        internal static string DisplayNameHTML {
            get {
                return ResourceManager.GetString("DisplayNameHTML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JavaScript.
        /// </summary>
        internal static string DisplayNameJavaScript {
            get {
                return ResourceManager.GetString("DisplayNameJavaScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL.
        /// </summary>
        internal static string DisplayNameSQL {
            get {
                return ResourceManager.GetString("DisplayNameSQL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft SQL Server Data Tools, T-SQL Language Services.
        /// </summary>
        internal static string DisplayNameSQLServerDataTools {
            get {
                return ResourceManager.GetString("DisplayNameSQLServerDataTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visual Basic.
        /// </summary>
        internal static string DisplayNameVisualBasic {
            get {
                return ResourceManager.GetString("DisplayNameVisualBasic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XAML.
        /// </summary>
        internal static string DisplayNameXAML {
            get {
                return ResourceManager.GetString("DisplayNameXAML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML.
        /// </summary>
        internal static string DisplayNameXML {
            get {
                return ResourceManager.GetString("DisplayNameXML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snippet File (*.snippet)
        ///*.snippet
        ///
        ///.
        /// </summary>
        internal static string EditorFormatString {
            get {
                return ResourceManager.GetString("EditorFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Empty {
            get {
                return ResourceManager.GetString("Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The automation model object was null.  Fatal Error..
        /// </summary>
        internal static string ErrorDTENull {
            get {
                return ResourceManager.GetString("ErrorDTENull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File IO Error.
        /// </summary>
        internal static string ErrorFileIO {
            get {
                return ResourceManager.GetString("ErrorFileIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The snippet file could not be loaded.  A blank snippet will be created instead..
        /// </summary>
        internal static string ErrorFileLoadFail {
            get {
                return ResourceManager.GetString("ErrorFileLoadFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid command ID for marker insertion!.
        /// </summary>
        internal static string ErrorInvalidMarkerID {
            get {
                return ResourceManager.GetString("ErrorInvalidMarkerID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; is an invalid replacement ID..
        /// </summary>
        internal static string ErrorInvalidReplacementID {
            get {
                return ResourceManager.GetString("ErrorInvalidReplacementID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid ProvideLanguageService argument.
        /// </summary>
        internal static string ErrorMarkerAttributeLanguageService {
            get {
                return ResourceManager.GetString("ErrorMarkerAttributeLanguageService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon localIcon {
            get {
                object obj = ResourceManager.GetObject("localIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File name cannot be null..
        /// </summary>
        internal static string NullFilename {
            get {
                return ResourceManager.GetString("NullFilename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This file has changed outside the editor. Do you wish to reload it?.
        /// </summary>
        internal static string OutsideEditorFileChange {
            get {
                return ResourceManager.GetString("OutsideEditorFileChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - {1}.
        /// </summary>
        internal static string PackageNameFormat {
            get {
                return ResourceManager.GetString("PackageNameFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Info.
        /// </summary>
        internal static string PropCategoryFileInfo {
            get {
                return ResourceManager.GetString("PropCategoryFileInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snippet Data.
        /// </summary>
        internal static string PropCategorySnippData {
            get {
                return ResourceManager.GetString("PropCategorySnippData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collection of alternative shortcuts used for executing the snippet.
        /// </summary>
        internal static string PropDescriptionSnippetAlternativeShortcuts {
            get {
                return ResourceManager.GetString("PropDescriptionSnippetAlternativeShortcuts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author of this snippet.
        /// </summary>
        internal static string PropDescriptionSnippetAuthor {
            get {
                return ResourceManager.GetString("PropDescriptionSnippetAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replacement Delimiter.
        /// </summary>
        internal static string PropDescriptionSnippetDelimiter {
            get {
                return ResourceManager.GetString("PropDescriptionSnippetDelimiter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description of this snippet.
        /// </summary>
        internal static string PropDescriptionSnippetDescription {
            get {
                return ResourceManager.GetString("PropDescriptionSnippetDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Url to locate more info about this snippets content.
        /// </summary>
        internal static string PropDescriptionSnippetHelpUrl {
            get {
                return ResourceManager.GetString("PropDescriptionSnippetHelpUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The collection of imports for this snippet..
        /// </summary>
        internal static string PropDescriptionSnippetImports {
            get {
                return ResourceManager.GetString("PropDescriptionSnippetImports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keywords that relate to this snippet.
        /// </summary>
        internal static string PropDescriptionSnippetKeywords {
            get {
                return ResourceManager.GetString("PropDescriptionSnippetKeywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kind of snippet.  \nNote: Only supported in Visual Basic.
        /// </summary>
        internal static string PropDescriptionSnippetKind {
            get {
                return ResourceManager.GetString("PropDescriptionSnippetKind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The full path to the snippet file.
        /// </summary>
        internal static string PropDescriptionSnippetPath {
            get {
                return ResourceManager.GetString("PropDescriptionSnippetPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The collection of references for this snippet..
        /// </summary>
        internal static string PropDescriptionSnippetReferences {
            get {
                return ResourceManager.GetString("PropDescriptionSnippetReferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The collection of replacements for this snippet.
        /// </summary>
        internal static string PropDescriptionSnippetReplacements {
            get {
                return ResourceManager.GetString("PropDescriptionSnippetReplacements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keyboard shortcut to insert this snippet.
        /// </summary>
        internal static string PropDescriptionSnippetShortcut {
            get {
                return ResourceManager.GetString("PropDescriptionSnippetShortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title of this snippet.
        /// </summary>
        internal static string PropDescriptionSnippetTitle {
            get {
                return ResourceManager.GetString("PropDescriptionSnippetTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of snippet.  \nEither expansion or surround with.\n Note: SurroundWith not supported in Visual Basic..
        /// </summary>
        internal static string PropDescriptionSnippetType {
            get {
                return ResourceManager.GetString("PropDescriptionSnippetType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alternative Shortcuts.
        /// </summary>
        internal static string PropNameSnippetAlternativeShortcuts {
            get {
                return ResourceManager.GetString("PropNameSnippetAlternativeShortcuts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author.
        /// </summary>
        internal static string PropNameSnippetAuthor {
            get {
                return ResourceManager.GetString("PropNameSnippetAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string PropNameSnippetDescription {
            get {
                return ResourceManager.GetString("PropNameSnippetDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help Url.
        /// </summary>
        internal static string PropNameSnippetHelpUrl {
            get {
                return ResourceManager.GetString("PropNameSnippetHelpUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imports.
        /// </summary>
        internal static string PropNameSnippetImports {
            get {
                return ResourceManager.GetString("PropNameSnippetImports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keywords.
        /// </summary>
        internal static string PropNameSnippetKeywords {
            get {
                return ResourceManager.GetString("PropNameSnippetKeywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snippet Kind.
        /// </summary>
        internal static string PropNameSnippetKind {
            get {
                return ResourceManager.GetString("PropNameSnippetKind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Path.
        /// </summary>
        internal static string PropNameSnippetPath {
            get {
                return ResourceManager.GetString("PropNameSnippetPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to References.
        /// </summary>
        internal static string PropNameSnippetReferences {
            get {
                return ResourceManager.GetString("PropNameSnippetReferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replacements.
        /// </summary>
        internal static string PropNameSnippetReplacements {
            get {
                return ResourceManager.GetString("PropNameSnippetReplacements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shortcut.
        /// </summary>
        internal static string PropNameSnippetShortcut {
            get {
                return ResourceManager.GetString("PropNameSnippetShortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string PropNameSnippetTitle {
            get {
                return ResourceManager.GetString("PropNameSnippetTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snippet Type.
        /// </summary>
        internal static string PropNameSnippetType {
            get {
                return ResourceManager.GetString("PropNameSnippetType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Literal.
        /// </summary>
        internal static string ReplacementLiteralName {
            get {
                return ResourceManager.GetString("ReplacementLiteralName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object.
        /// </summary>
        internal static string ReplacementObjectName {
            get {
                return ResourceManager.GetString("ReplacementObjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Snippet As.
        /// </summary>
        internal static string SaveDialogText {
            get {
                return ResourceManager.GetString("SaveDialogText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected error from the source control provider..
        /// </summary>
        internal static string SCCError {
            get {
                return ResourceManager.GetString("SCCError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defaults to.
        /// </summary>
        internal static string SnippetFormColumnHeaderDefault {
            get {
                return ResourceManager.GetString("SnippetFormColumnHeaderDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editable.
        /// </summary>
        internal static string SnippetFormColumnHeaderEditable {
            get {
                return ResourceManager.GetString("SnippetFormColumnHeaderEditable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Function.
        /// </summary>
        internal static string SnippetFormColumnHeaderFunction {
            get {
                return ResourceManager.GetString("SnippetFormColumnHeaderFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        internal static string SnippetFormColumnHeaderID {
            get {
                return ResourceManager.GetString("SnippetFormColumnHeaderID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kind.
        /// </summary>
        internal static string SnippetFormColumnHeaderReplacementKind {
            get {
                return ResourceManager.GetString("SnippetFormColumnHeaderReplacementKind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tooltip.
        /// </summary>
        internal static string SnippetFormColumnHeaderTooltip {
            get {
                return ResourceManager.GetString("SnippetFormColumnHeaderTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string SnippetFormColumnHeaderType {
            get {
                return ResourceManager.GetString("SnippetFormColumnHeaderType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language: .
        /// </summary>
        internal static string SnippetFormLanguageLabelText {
            get {
                return ResourceManager.GetString("SnippetFormLanguageLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replacements.
        /// </summary>
        internal static string SnippetFormReplacementLabelText {
            get {
                return ResourceManager.GetString("SnippetFormReplacementLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snippet File|*.snippet|All Files|*.*.
        /// </summary>
        internal static string SnippetFormSaveFilter {
            get {
                return ResourceManager.GetString("SnippetFormSaveFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The deafult value of the id.
        /// </summary>
        internal static string SnippetFormTipDefault {
            get {
                return ResourceManager.GetString("SnippetFormTipDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is this replacement editable?.
        /// </summary>
        internal static string SnippetFormTipEditable {
            get {
                return ResourceManager.GetString("SnippetFormTipEditable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A predefined function to use.
        /// </summary>
        internal static string SnippetFormTipFunction {
            get {
                return ResourceManager.GetString("SnippetFormTipFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The replacement ID.
        /// </summary>
        internal static string SnippetFormTipID {
            get {
                return ResourceManager.GetString("SnippetFormTipID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is your replacement a Literal or Object?.
        /// </summary>
        internal static string SnippetFormTipReplacementKind {
            get {
                return ResourceManager.GetString("SnippetFormTipReplacementKind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What type is the object?.
        /// </summary>
        internal static string SnippetFormTipReplacementType {
            get {
                return ResourceManager.GetString("SnippetFormTipReplacementType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tooltip shown in code editor.
        /// </summary>
        internal static string SnippetFormTipToolTip {
            get {
                return ResourceManager.GetString("SnippetFormTipToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snippet:.
        /// </summary>
        internal static string SnippetFormTitlesLabelText {
            get {
                return ResourceManager.GetString("SnippetFormTitlesLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snippet Replacement Marker.
        /// </summary>
        internal static string SnippetReplacementMarker {
            get {
                return ResourceManager.GetString("SnippetReplacementMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A marker to highlight replacements.
        /// </summary>
        internal static string SnippetReplacementMarkerDescription {
            get {
                return ResourceManager.GetString("SnippetReplacementMarkerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A replacement.
        /// </summary>
        internal static string SnippetReplacementMarkerText {
            get {
                return ResourceManager.GetString("SnippetReplacementMarkerText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snippet Explorer.
        /// </summary>
        internal static string ToolWindowTitle {
            get {
                return ResourceManager.GetString("ToolWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N/A.
        /// </summary>
        internal static string TypeInvalidForLiteralSymbol {
            get {
                return ResourceManager.GetString("TypeInvalidForLiteralSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown format..
        /// </summary>
        internal static string UnknownFileFormat {
            get {
                return ResourceManager.GetString("UnknownFileFormat", resourceCulture);
            }
        }
    }
}
