//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1434
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.SnippetDesigner {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ConstantStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ConstantStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.SnippetDesigner.ConstantStrings", typeof(ConstantStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  .
        /// </summary>
        internal static string ArgumentStartMarker {
            get {
                return ResourceManager.GetString("ArgumentStartMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DefaultsTo.
        /// </summary>
        internal static string ColumnDefault {
            get {
                return ResourceManager.GetString("ColumnDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editable.
        /// </summary>
        internal static string ColumnEditable {
            get {
                return ResourceManager.GetString("ColumnEditable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Function.
        /// </summary>
        internal static string ColumnFunction {
            get {
                return ResourceManager.GetString("ColumnFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        internal static string ColumnID {
            get {
                return ResourceManager.GetString("ColumnID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReplacementKind.
        /// </summary>
        internal static string ColumnReplacementKind {
            get {
                return ResourceManager.GetString("ColumnReplacementKind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tooltip.
        /// </summary>
        internal static string ColumnTooltip {
            get {
                return ResourceManager.GetString("ColumnTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string ColumnType {
            get {
                return ResourceManager.GetString("ColumnType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SnippetEditorConfig.xml.
        /// </summary>
        internal static string ConfigurationFile {
            get {
                return ResourceManager.GetString("ConfigurationFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;.
        /// </summary>
        internal static string DoubleQuoteString {
            get {
                return ResourceManager.GetString("DoubleQuoteString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to csharp.
        /// </summary>
        internal static string ExportNameCSharp {
            get {
                return ResourceManager.GetString("ExportNameCSharp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to visual jsharp.
        /// </summary>
        internal static string ExportNameJSharp {
            get {
                return ResourceManager.GetString("ExportNameJSharp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to basic.
        /// </summary>
        internal static string ExportNameVisualBasic {
            get {
                return ResourceManager.GetString("ExportNameVisualBasic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xml.
        /// </summary>
        internal static string ExportNameXML {
            get {
                return ResourceManager.GetString("ExportNameXML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Code Snippets.
        /// </summary>
        internal static string MySnippetsDir {
            get {
                return ResourceManager.GetString("MySnippetsDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Xml Snippets.
        /// </summary>
        internal static string MyXmlSnippetsDir {
            get {
                return ResourceManager.GetString("MyXmlSnippetsDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to csharp.
        /// </summary>
        internal static string SchemaNameCSharp {
            get {
                return ResourceManager.GetString("SchemaNameCSharp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vcsharp.
        /// </summary>
        internal static string SchemaNameCSharp2 {
            get {
                return ResourceManager.GetString("SchemaNameCSharp2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb.
        /// </summary>
        internal static string SchemaNameVisualBasic {
            get {
                return ResourceManager.GetString("SchemaNameVisualBasic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xml.
        /// </summary>
        internal static string SchemaNameXML {
            get {
                return ResourceManager.GetString("SchemaNameXML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code Snippets.
        /// </summary>
        internal static string SnippetDirectoryName {
            get {
                return ResourceManager.GetString("SnippetDirectoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visual C#.
        /// </summary>
        internal static string SnippetDirNameCSharp {
            get {
                return ResourceManager.GetString("SnippetDirNameCSharp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visual Basic.
        /// </summary>
        internal static string SnippetDirNameVisualBasic {
            get {
                return ResourceManager.GetString("SnippetDirNameVisualBasic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML.
        /// </summary>
        internal static string SnippetDirNameXML {
            get {
                return ResourceManager.GetString("SnippetDirNameXML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expansion.
        /// </summary>
        internal static string SnippetTypeExpansion {
            get {
                return ResourceManager.GetString("SnippetTypeExpansion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to method body.
        /// </summary>
        internal static string SnippetTypeMethodBody {
            get {
                return ResourceManager.GetString("SnippetTypeMethodBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to method decl.
        /// </summary>
        internal static string SnippetTypeMethodDeclaration {
            get {
                return ResourceManager.GetString("SnippetTypeMethodDeclaration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to type decl.
        /// </summary>
        internal static string SnippetTypeTypeDeclaration {
            get {
                return ResourceManager.GetString("SnippetTypeTypeDeclaration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $end$.
        /// </summary>
        internal static string SymbolEnd {
            get {
                return ResourceManager.GetString("SymbolEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to end.
        /// </summary>
        internal static string SymbolEndWord {
            get {
                return ResourceManager.GetString("SymbolEndWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $.
        /// </summary>
        internal static string SymbolReplacement {
            get {
                return ResourceManager.GetString("SymbolReplacement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $selected$.
        /// </summary>
        internal static string SymbolSelected {
            get {
                return ResourceManager.GetString("SymbolSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to selected.
        /// </summary>
        internal static string SymbolSelectedWord {
            get {
                return ResourceManager.GetString("SymbolSelectedWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^((&quot;.*&quot;)|(\w+))$.
        /// </summary>
        internal static string ValidReplacementString {
            get {
                return ResourceManager.GetString("ValidReplacementString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VC#.
        /// </summary>
        internal static string VSCSharpDirName {
            get {
                return ResourceManager.GetString("VSCSharpDirName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VJ#.
        /// </summary>
        internal static string VSJSharpDirName {
            get {
                return ResourceManager.GetString("VSJSharpDirName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VisualStudioLocation.
        /// </summary>
        internal static string VSRegistryLocationEntry {
            get {
                return ResourceManager.GetString("VSRegistryLocationEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOFTWARE\Microsoft\VisualStudio\9.0.
        /// </summary>
        internal static string VSRegistryPath {
            get {
                return ResourceManager.GetString("VSRegistryPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration.
        /// </summary>
        internal static string VSRegistryRegistrationName {
            get {
                return ResourceManager.GetString("VSRegistryRegistrationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserName.
        /// </summary>
        internal static string VSRegistryRegistrationNameEntry {
            get {
                return ResourceManager.GetString("VSRegistryRegistrationNameEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snippets.
        /// </summary>
        internal static string VSSnippetDir {
            get {
                return ResourceManager.GetString("VSSnippetDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VB.
        /// </summary>
        internal static string VSVBDirName {
            get {
                return ResourceManager.GetString("VSVBDirName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xml.
        /// </summary>
        internal static string VSXmlDirName {
            get {
                return ResourceManager.GetString("VSXmlDirName", resourceCulture);
            }
        }
    }
}
